nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
imagePullPolicy: IfNotPresent

global:
  image:
    registry: swr.cn-east-3.myhuaweicloud.com/chaitin-safeline
    tag: ""
  # 全局开启已端口模式暴露服务，牵扯修改服务暴露模式服务为：detector与chaos，打开此选项将增加多个configmap加载以及修改配置文件，会修改nginx.conf文件。
  # 建议此向保持开启状态
  exposeServicesAsPorts:
    enabled: true
  # 设置雷池WAF控制台通过域名访问，如：demo.waf-ce.chaitin.cn
  ingress:
    # 是否开启雷池WAF控制通过域名访问，默认未开启
    enabled: false
    hostname: waf.local
    ingressClassName: nginx
    annotations:
      # 注释中的proxy-body-size的存储值，文件上传大小的最大值，即nginx.ingress.kubernetes.io/proxy-body-size的值，默认为200M
      proxyBodySize: 200M
    pathType: ImplementationSpecific
    path: /
    tls:
      # 是否加载HelmChart外部的HTTPS域名证书Secret,如果有请填写Secret名称，默认不填写及域名仅开启http访问.
      # 如填写如下项，请在运行该HelmChart前创建好对应的Secret。
      secretName: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      annotations: {}

    detectorLogs:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    tengineLogs:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    nginx:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    mgt:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    detector:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    tengine:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    luigi:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}
    
    chaos:
      existingClaim: ""
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

database:
  type: internal
  internal:
    serviceAccountName: ""
    automountServiceAccountToken: false
    image:
      registry: ''
      repository: postgres
      tag: 15.2
    password: changeit
    shmSizeLimit: 512Mi
    resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    livenessProbe:
      timeoutSeconds: 1
    readinessProbe:
      timeoutSeconds: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName:
    initContainer:
      migrator: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
      permissions: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
  external:
    host: ""
    port: ""
    username: ""
    password: ""
    coreDatabase: "safeline-ce"
    dbname: "safeline-ce"
    existingSecret: ""
    sslmode: "disable"
  maxIdleConns: 100
  maxOpenConns: 900
  podAnnotations: {}

mgt:
  image:
    registry: ''
    repository: safeline-mgt
    tag: ""
  service:
    type: NodePort
    web:
      nodePort: 31443
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

fvm:
  image:
    registry: ''
    repository: safeline-fvm
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 


detector:
  image:
    registry: ''
    repository: safeline-detector
    tag: ""
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

tengine:
  image:
    registry: ''
    repository: safeline-tengine
    tag: ""
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

luigi:
  image:
    registry: ''
    repository: safeline-luigi
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

chaos:
  image:
    registry: ''
    repository: safeline-chaos
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 
