apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "safeline.tengine" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: tengine
spec:
  replicas: {{ .Values.tengine.replicas }}
  revisionHistoryLimit: {{ .Values.tengine.revisionHistoryLimit }}
  strategy:
{{- if .Values.strategy }}
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
{{ include "safeline.matchLabels" . | indent 6 }}
      component: tengine
  template:
    metadata:
      labels:
{{ include "safeline.matchLabels" . | indent 8 }}
        component: tengine
      annotations:
{{- if .Values.tengine.podAnnotations }}
{{ toYaml .Values.tengine.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.tengine.serviceAccountName }}
      serviceAccountName: {{ .Values.tengine.serviceAccountName }}
{{- end -}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.tengine.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: tengine
        image: {{ default .Values.global.image.registry .Values.tengine.image.registry }}/{{ .Values.tengine.image.repository }}{{ .Values.global.image.region }}:{{ default .Chart.AppVersion .Values.tengine.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.global.exposeServicesAsPorts.enabled }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/modify_nginx_conf.sh"]
        {{- end }}
        ports:
          - name: health
            containerPort: {{ template "safeline.tengine.health.port" . }}
          - name: http
            containerPort: {{ template "safeline.tengine.http.port" . }}
          - name: tasktcd
            containerPort: {{ template "safeline.tengine.tasktcd.port" . }}
        envFrom:
        - configMapRef:
            name: {{ template "safeline.tengine.env" . }}
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - mountPath: /etc/nginx
            name: nginx
          - mountPath: /resources/detector
            name: detector
          - mountPath: /var/log/nginx
            name: logs
          - mountPath: /usr/local/nginx/cache
            name: cache
          - mountPath: /resources/chaos
            name: chaos
          - mountPath: /app/sock
            name: tengine-sock-dir
          {{- if .Values.global.exposeServicesAsPorts.enabled }}
          - name: safeline-k8s
            mountPath: /safeline_k8s.conf
            subPath: safeline_k8s.conf
          - name: safeline-tengine-modify-conf
            mountPath: /modify_nginx_conf.sh
            subPath: modify_nginx_conf.sh
          {{- end }}
        readinessProbe:
          tcpSocket:
            port: {{ template "safeline.tengine.health.port" . }}
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
{{- if .Values.tengine.resources }}
        resources:
{{ toYaml .Values.tengine.resources | indent 10 }}
{{- end }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        {{- if .Values.persistence.enabled }}
        - name: nginx
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.nginx.existingClaim | default (include "safeline.nginx" .) }}
        - name: detector
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.detector.existingClaim | default (include "safeline.detector" .) }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.tengineLogs.existingClaim | default (include "safeline.tengine-logs" .) }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.tengine.existingClaim | default (include "safeline.tengine" .) }}
        - name: chaos
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.chaos.existingClaim | default (include "safeline.chaos" .) }}
        - name: tengine-sock-dir
          emptyDir: {}
        {{- if .Values.global.exposeServicesAsPorts.enabled }}
        - name: safeline-k8s
          configMap:
            name: {{ template "safeline.tengine" . }}
        - name: safeline-tengine-modify-conf
          configMap:
            name: safeline-tengine-modify-conf
            defaultMode: 0755
        {{- end -}}
        {{- else -}}
        - name: nginx
          emptyDir: {}
        - name: detector
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: chaos
          emptyDir: {}
        {{- end -}}

    {{- with .Values.tengine.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tengine.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tengine.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.tengine.priorityClassName }}
      priorityClassName: {{ .Values.tengine.priorityClassName }}
    {{- end }}
