{{- if .Values.global.exposeServicesAsPorts.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "safeline.tengine" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
data:
  safeline_k8s.conf: |
    upstream detector_server {
        keepalive   256;
        server      {{ template "safeline.detector" . }}:{{ template "safeline.detector.tcd.port" . }};
    }

    upstream chaos_server {
        keepalive   256;
        server     {{ template "safeline.chaos" . }}:{{ template "safeline.stpp.port" . }};
    }

    upstream wr_server {
        keepalive   256;
        server    {{ template "safeline.chaos" . }}:{{ template "safeline.wrtcp.port" . }};
    }

    t1k_intercept @safeline; # enable request detection
    t1k_body_size 1m;        # max forward size of request body

    tx_intercept @safelinex; # enable response detection
    tx_body_size 1m;         # max forward size of response body

    tx_chaos_intercept @safeline_chaos; # enable response chaos
    tx_chaos_body_size 10m;             # max forward size of response body for chaos

    t1k_wr_intercept @safeline_wr;

    include tx_ignore_types;

    t1k_ulog 10000;
    t1k_stat 10000;          # enable nginx stat info

    t1k_extra_header on;
    t1k_extra_body on;

    foreach_server {
        location @safeline {
            internal;
            t1k_pass detector_server;
            t1k_connect_timeout 1s;
            t1k_read_timeout 1s;
            t1k_send_timeout 1s;
        }
        location @safelinex {
            internal;
            tx_pass detector_server;
            tx_connect_timeout 1s;
            tx_read_timeout 1s;
            tx_send_timeout 1s;
        }
        location @safeline_chaos {
            internal;
            tx_chaos_pass chaos_server;
            tx_chaos_read_timeout 3s;
            tx_chaos_send_timeout 3s;
            tx_chaos_connect_timeout 3s;
        }
        location @safeline_wr {
            internal;
            t1k_wr_pass wr_server;
            t1k_wr_read_timeout 3s;
            t1k_wr_send_timeout 3s;
            t1k_wr_connect_timeout 3s;
        }
    }
{{- end }}