apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "safeline.chaos" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
    component: chaos
spec:
  replicas: {{ .Values.chaos.replicas }}
  revisionHistoryLimit: {{ .Values.chaos.revisionHistoryLimit }}
  strategy:
{{- if .Values.strategy }}
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
{{ include "safeline.matchLabels" . | indent 6 }}
      component: chaos
  template:
    metadata:
      labels:
{{ include "safeline.matchLabels" . | indent 8 }}
        component: chaos
      annotations:
{{- if .Values.chaos.podAnnotations }}
{{ toYaml .Values.chaos.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.chaos.serviceAccountName }}
      serviceAccountName: {{ .Values.chaos.serviceAccountName }}
{{- end -}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.chaos.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      {{- if .Values.global.exposeServicesAsPorts.enabled }}
      initContainers:
      - name: cp-chaos-toml-file
        image: busybox
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - sh
          - -c
          - |-
            sleep 3 && /bin/sh /cp_config_toml.sh
        volumeMounts:
          - mountPath: /app/chaos
            name: chaos
          - name: chaos-conf
            mountPath: /config.toml
            subPath: config.toml
          - name: chaos-wr-conf
            mountPath: /waiting.yaml
            subPath: waiting.yaml
          - name: chaos-challenge-conf
            mountPath: /challenge.yaml
            subPath: challenge.yaml
          - name: safeline-chaos-cp-toml
            mountPath: /cp_config_toml.sh
            subPath: cp_config_toml.sh
      {{- end }}
      containers:
      - name: chaos
        image: {{ default .Values.global.image.registry .Values.chaos.image.registry }}/{{ .Values.chaos.image.repository }}:{{ default .Chart.AppVersion .Values.chaos.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
          - name: stpp
            containerPort: {{ template "safeline.stpp.port" . }}
          - name: http
            containerPort: {{ template "safeline.http.port" . }}
        envFrom:
        - configMapRef:
            name: {{ template "safeline.chaos.env" . }}
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - mountPath: /app/chaos
            name: chaos
        readinessProbe:
          tcpSocket:
            port: {{ template "safeline.http.port" . }}
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
{{- if .Values.chaos.resources }}
        resources:
{{ toYaml .Values.chaos.resources | indent 10 }}
{{- end }}
      volumes:
        {{- if .Values.global.exposeServicesAsPorts.enabled }}
        - name: chaos-conf
          configMap:
            name: {{ template "safeline.chaos" . }}
        - name: chaos-wr-conf
          configMap:
            name: {{ template "safeline.chaos" . }}
        - name: chaos-challenge-conf
          configMap:
            name: {{ template "safeline.chaos" . }}
        - name: safeline-chaos-cp-toml
          configMap:
            name: safeline-chaos-cp-toml
            defaultMode: 0755
        {{- end }}
        - name: localtime
          hostPath:
            path: /etc/localtime
        {{- if .Values.persistence.enabled }}
        - name: chaos
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.chaos.existingClaim | default (include "safeline.chaos" .) }}
        {{- else -}}
        - name: chaos
          emptyDir: {}
        {{- end -}}
    {{- with .Values.chaos.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.chaos.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.chaos.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.chaos.priorityClassName }}
      priorityClassName: {{ .Values.chaos.priorityClassName }}
    {{- end }}
